name: Build and Deploy to AKS

on:
  push:
    branches:
      - main   # Trigger workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'  # Specify Java distribution
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install -DskipTests   # Skip tests since no database is used
      working-directory: ./automation       # Set working directory to /automation

    - name: Build Docker image
      run: docker build -t sahilshah989/java-app:latest .
      working-directory: ./automation       # Set working directory to /automation

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push sahilshah989/java-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS Context
      run: az aks get-credentials --resource-group vibha --name AKSCluster

    - name: Deploy the application to AKS
      run: |
        kubectl apply -f app-deployment.yaml
        kubectl apply -f app-service.yaml

    - name: Wait for 10 seconds
      run: sleep 10
 
    - name: Verify Deployment
      run: kubectl get all
