name: Build and Deploy to AKS

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image using Docker Compose
      run: |
        kubectl apply -f ./automation/docker-compose.yml build
        kubectl apply -f ./automation/docker-compose.yml push

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS Context
      run: az aks get-credentials --resource-group vibha --name AKSCluster

    - name: Deploy the application to AKS
      run: |
        kubectl apply -f ./automation/deployment.yml
        kubectl apply -f ./automation/service.yml

    - name: Wait for 10 seconds
      run: sleep 10

    - name: Verify Deployment
      run: kubectl get all
